// <auto-generated />
using Demo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Demo.Migrations
{
    [DbContext(typeof(BetContext))]
    partial class BetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo.Models.Bet", b =>
                {
                    b.Property<long>("BetId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<long>("EventId");

                    b.Property<long>("PlayerId");

                    b.Property<byte>("Type");

                    b.HasKey("BetId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("Demo.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("AwayOdds");

                    b.Property<string>("AwayTeam");

                    b.Property<float>("DrawOdds");

                    b.Property<float>("HomeOdds");

                    b.Property<string>("HomeTeam");

                    b.Property<DateTime>("KickoffTime");

                    b.Property<byte>("Result");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Demo.Models.Player", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Demo.Models.PlayerInfo", b =>
                {
                    b.Property<long>("PlayerInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AmountLost");

                    b.Property<double>("AmountWon");

                    b.Property<long?>("PlayerId");

                    b.Property<long>("TotalBets");

                    b.Property<long>("TotalBetsLost");

                    b.Property<long>("TotalBetsWon");

                    b.HasKey("PlayerInfoId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerInfos");
                });

            modelBuilder.Entity("Demo.Models.PlayerInfo", b =>
                {
                    b.HasOne("Demo.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
